// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18_nAFNwDXvPnI6s3LFyf0AsMzOAhqBc',
    appId: '1:460591389535:web:90a4e9d6bf112f644f74ea',
    messagingSenderId: '460591389535',
    projectId: 'parking-4292e',
    authDomain: 'parking-4292e.firebaseapp.com',
    storageBucket: 'parking-4292e.appspot.com',
    measurementId: 'G-1W0Z34FJW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95cUHHoHhjFEmfRgskXR31nwJ3gUMmgg',
    appId: '1:460591389535:android:90ee53dca4dc0b0e4f74ea',
    messagingSenderId: '460591389535',
    projectId: 'parking-4292e',
    storageBucket: 'parking-4292e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PIxKAk_10INuiPNn5pM612N7NSCBVNI',
    appId: '1:460591389535:ios:1ee701c86f2344474f74ea',
    messagingSenderId: '460591389535',
    projectId: 'parking-4292e',
    storageBucket: 'parking-4292e.appspot.com',
    iosClientId: '460591389535-0ji7refq9kcudolsd8c2ekr9tropathu.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationApp',
  );
}
